version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        environment:
            - DEBUG=1
        depends_on:
            - mysql
            - mysql-integration-test
            - redis
            - rabbitmq
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - redis-net
            - mariadb-net
            - rabbit-net
            - mariadb-net-integration-test

    redis:
        image: redis
        restart: always
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
            - redis-net
        volumes:
            - redis-data:/data

    mysql:
        image: mariadb:10.4
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_ROOT_HOST=%
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - mariadb-net

    mysql-integration-test:
        image: mariadb:10.4
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=app
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_ROOT_HOST=%
        volumes:
            - dbdataintegrationtest:/var/lib/mysql
        networks:
            - mariadb-net-integration-test

    rabbitmq:
        image: rabbitmq:latest
        restart: always
        networks:
            - rabbit-net

volumes:
    redis-data:
    dbdata:
    dbdataintegrationtest:

networks:
    redis-net:
    mariadb-net:
    rabbit-net:
    mariadb-net-integration-test:
