services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    behatch.http_call.request.pool:
        class: Behatch\HttpCall\HttpCallResultPool
        public: false

    Behatch\HttpCall\HttpCallResultPool:
        alias: behatch.http_call.request.pool

    behatch.http_call.request:
        class: Behatch\HttpCall\Request
        arguments:
            - '@behat.mink'
        public: false

    Behatch\HttpCall\Request:
        alias: behatch.http_call.request
